// api/proto/cbi/v1/cbi.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/proto/cbi/v1/cbi.proto

package cbiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CBISimulator_FrameStream_FullMethodName        = "/cbi.v1.CBISimulator/FrameStream"
	CBISimulator_GetDeviceState_FullMethodName     = "/cbi.v1.CBISimulator/GetDeviceState"
	CBISimulator_SetDeviceState_FullMethodName     = "/cbi.v1.CBISimulator/SetDeviceState"
	CBISimulator_GetAllDeviceStates_FullMethodName = "/cbi.v1.CBISimulator/GetAllDeviceStates"
	CBISimulator_SetRole_FullMethodName            = "/cbi.v1.CBISimulator/SetRole"
	CBISimulator_GetRole_FullMethodName            = "/cbi.v1.CBISimulator/GetRole"
	CBISimulator_LoadScenario_FullMethodName       = "/cbi.v1.CBISimulator/LoadScenario"
	CBISimulator_SaveScenario_FullMethodName       = "/cbi.v1.CBISimulator/SaveScenario"
	CBISimulator_DeleteScenario_FullMethodName     = "/cbi.v1.CBISimulator/DeleteScenario"
	CBISimulator_ListScenarios_FullMethodName      = "/cbi.v1.CBISimulator/ListScenarios"
)

// CBISimulatorClient is the client API for CBISimulator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CBISimulatorClient interface {
	// 双向流：帧收发（主通信通道）
	FrameStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FrameRequest, FrameResponse], error)
	// 设备状态管理
	GetDeviceState(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (*DeviceState, error)
	SetDeviceState(ctx context.Context, in *SetDeviceRequest, opts ...grpc.CallOption) (*SetDeviceResponse, error)
	GetAllDeviceStates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllDeviceStates, error)
	// 角色控制
	SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*RoleResponse, error)
	GetRole(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RoleResponse, error)
	// 场景管理
	LoadScenario(ctx context.Context, in *ScenarioRequest, opts ...grpc.CallOption) (*ScenarioResponse, error)
	SaveScenario(ctx context.Context, in *ScenarioRequest, opts ...grpc.CallOption) (*ScenarioResponse, error)
	DeleteScenario(ctx context.Context, in *ScenarioRequest, opts ...grpc.CallOption) (*ScenarioResponse, error)
	ListScenarios(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ScenarioListResponse, error)
}

type cBISimulatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCBISimulatorClient(cc grpc.ClientConnInterface) CBISimulatorClient {
	return &cBISimulatorClient{cc}
}

func (c *cBISimulatorClient) FrameStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FrameRequest, FrameResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CBISimulator_ServiceDesc.Streams[0], CBISimulator_FrameStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FrameRequest, FrameResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CBISimulator_FrameStreamClient = grpc.BidiStreamingClient[FrameRequest, FrameResponse]

func (c *cBISimulatorClient) GetDeviceState(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (*DeviceState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceState)
	err := c.cc.Invoke(ctx, CBISimulator_GetDeviceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cBISimulatorClient) SetDeviceState(ctx context.Context, in *SetDeviceRequest, opts ...grpc.CallOption) (*SetDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDeviceResponse)
	err := c.cc.Invoke(ctx, CBISimulator_SetDeviceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cBISimulatorClient) GetAllDeviceStates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllDeviceStates, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllDeviceStates)
	err := c.cc.Invoke(ctx, CBISimulator_GetAllDeviceStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cBISimulatorClient) SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*RoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleResponse)
	err := c.cc.Invoke(ctx, CBISimulator_SetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cBISimulatorClient) GetRole(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleResponse)
	err := c.cc.Invoke(ctx, CBISimulator_GetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cBISimulatorClient) LoadScenario(ctx context.Context, in *ScenarioRequest, opts ...grpc.CallOption) (*ScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScenarioResponse)
	err := c.cc.Invoke(ctx, CBISimulator_LoadScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cBISimulatorClient) SaveScenario(ctx context.Context, in *ScenarioRequest, opts ...grpc.CallOption) (*ScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScenarioResponse)
	err := c.cc.Invoke(ctx, CBISimulator_SaveScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cBISimulatorClient) DeleteScenario(ctx context.Context, in *ScenarioRequest, opts ...grpc.CallOption) (*ScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScenarioResponse)
	err := c.cc.Invoke(ctx, CBISimulator_DeleteScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cBISimulatorClient) ListScenarios(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ScenarioListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScenarioListResponse)
	err := c.cc.Invoke(ctx, CBISimulator_ListScenarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CBISimulatorServer is the server API for CBISimulator service.
// All implementations must embed UnimplementedCBISimulatorServer
// for forward compatibility.
type CBISimulatorServer interface {
	// 双向流：帧收发（主通信通道）
	FrameStream(grpc.BidiStreamingServer[FrameRequest, FrameResponse]) error
	// 设备状态管理
	GetDeviceState(context.Context, *DeviceRequest) (*DeviceState, error)
	SetDeviceState(context.Context, *SetDeviceRequest) (*SetDeviceResponse, error)
	GetAllDeviceStates(context.Context, *Empty) (*AllDeviceStates, error)
	// 角色控制
	SetRole(context.Context, *SetRoleRequest) (*RoleResponse, error)
	GetRole(context.Context, *Empty) (*RoleResponse, error)
	// 场景管理
	LoadScenario(context.Context, *ScenarioRequest) (*ScenarioResponse, error)
	SaveScenario(context.Context, *ScenarioRequest) (*ScenarioResponse, error)
	DeleteScenario(context.Context, *ScenarioRequest) (*ScenarioResponse, error)
	ListScenarios(context.Context, *Empty) (*ScenarioListResponse, error)
	mustEmbedUnimplementedCBISimulatorServer()
}

// UnimplementedCBISimulatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCBISimulatorServer struct{}

func (UnimplementedCBISimulatorServer) FrameStream(grpc.BidiStreamingServer[FrameRequest, FrameResponse]) error {
	return status.Error(codes.Unimplemented, "method FrameStream not implemented")
}
func (UnimplementedCBISimulatorServer) GetDeviceState(context.Context, *DeviceRequest) (*DeviceState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceState not implemented")
}
func (UnimplementedCBISimulatorServer) SetDeviceState(context.Context, *SetDeviceRequest) (*SetDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDeviceState not implemented")
}
func (UnimplementedCBISimulatorServer) GetAllDeviceStates(context.Context, *Empty) (*AllDeviceStates, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllDeviceStates not implemented")
}
func (UnimplementedCBISimulatorServer) SetRole(context.Context, *SetRoleRequest) (*RoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRole not implemented")
}
func (UnimplementedCBISimulatorServer) GetRole(context.Context, *Empty) (*RoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRole not implemented")
}
func (UnimplementedCBISimulatorServer) LoadScenario(context.Context, *ScenarioRequest) (*ScenarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadScenario not implemented")
}
func (UnimplementedCBISimulatorServer) SaveScenario(context.Context, *ScenarioRequest) (*ScenarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveScenario not implemented")
}
func (UnimplementedCBISimulatorServer) DeleteScenario(context.Context, *ScenarioRequest) (*ScenarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteScenario not implemented")
}
func (UnimplementedCBISimulatorServer) ListScenarios(context.Context, *Empty) (*ScenarioListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScenarios not implemented")
}
func (UnimplementedCBISimulatorServer) mustEmbedUnimplementedCBISimulatorServer() {}
func (UnimplementedCBISimulatorServer) testEmbeddedByValue()                      {}

// UnsafeCBISimulatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CBISimulatorServer will
// result in compilation errors.
type UnsafeCBISimulatorServer interface {
	mustEmbedUnimplementedCBISimulatorServer()
}

func RegisterCBISimulatorServer(s grpc.ServiceRegistrar, srv CBISimulatorServer) {
	// If the following call panics, it indicates UnimplementedCBISimulatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CBISimulator_ServiceDesc, srv)
}

func _CBISimulator_FrameStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CBISimulatorServer).FrameStream(&grpc.GenericServerStream[FrameRequest, FrameResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CBISimulator_FrameStreamServer = grpc.BidiStreamingServer[FrameRequest, FrameResponse]

func _CBISimulator_GetDeviceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CBISimulatorServer).GetDeviceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CBISimulator_GetDeviceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CBISimulatorServer).GetDeviceState(ctx, req.(*DeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CBISimulator_SetDeviceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CBISimulatorServer).SetDeviceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CBISimulator_SetDeviceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CBISimulatorServer).SetDeviceState(ctx, req.(*SetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CBISimulator_GetAllDeviceStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CBISimulatorServer).GetAllDeviceStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CBISimulator_GetAllDeviceStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CBISimulatorServer).GetAllDeviceStates(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CBISimulator_SetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CBISimulatorServer).SetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CBISimulator_SetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CBISimulatorServer).SetRole(ctx, req.(*SetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CBISimulator_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CBISimulatorServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CBISimulator_GetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CBISimulatorServer).GetRole(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CBISimulator_LoadScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CBISimulatorServer).LoadScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CBISimulator_LoadScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CBISimulatorServer).LoadScenario(ctx, req.(*ScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CBISimulator_SaveScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CBISimulatorServer).SaveScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CBISimulator_SaveScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CBISimulatorServer).SaveScenario(ctx, req.(*ScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CBISimulator_DeleteScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CBISimulatorServer).DeleteScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CBISimulator_DeleteScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CBISimulatorServer).DeleteScenario(ctx, req.(*ScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CBISimulator_ListScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CBISimulatorServer).ListScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CBISimulator_ListScenarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CBISimulatorServer).ListScenarios(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CBISimulator_ServiceDesc is the grpc.ServiceDesc for CBISimulator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CBISimulator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cbi.v1.CBISimulator",
	HandlerType: (*CBISimulatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceState",
			Handler:    _CBISimulator_GetDeviceState_Handler,
		},
		{
			MethodName: "SetDeviceState",
			Handler:    _CBISimulator_SetDeviceState_Handler,
		},
		{
			MethodName: "GetAllDeviceStates",
			Handler:    _CBISimulator_GetAllDeviceStates_Handler,
		},
		{
			MethodName: "SetRole",
			Handler:    _CBISimulator_SetRole_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _CBISimulator_GetRole_Handler,
		},
		{
			MethodName: "LoadScenario",
			Handler:    _CBISimulator_LoadScenario_Handler,
		},
		{
			MethodName: "SaveScenario",
			Handler:    _CBISimulator_SaveScenario_Handler,
		},
		{
			MethodName: "DeleteScenario",
			Handler:    _CBISimulator_DeleteScenario_Handler,
		},
		{
			MethodName: "ListScenarios",
			Handler:    _CBISimulator_ListScenarios_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FrameStream",
			Handler:       _CBISimulator_FrameStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/cbi/v1/cbi.proto",
}
