// api/proto/cbi/v1/cbi.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/cbi/v1/cbi.proto

package cbiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 帧类型枚举
type FrameType int32

const (
	FrameType_FRAME_TYPE_UNSPECIFIED FrameType = 0
	// 通信控制帧
	FrameType_FRAME_TYPE_DC2    FrameType = 18 // 0x12 - 连接请求
	FrameType_FRAME_TYPE_DC3    FrameType = 19 // 0x13 - 连接确认
	FrameType_FRAME_TYPE_ACK    FrameType = 6  // 0x06 - 应答/心跳
	FrameType_FRAME_TYPE_NACK   FrameType = 21 // 0x15 - 否定应答
	FrameType_FRAME_TYPE_VERROR FrameType = 16 // 0x10 - 版本错误
	// 数据传送帧
	FrameType_FRAME_TYPE_SDCI FrameType = 138 // 0x8A - 站场数据变化(增量)
	FrameType_FRAME_TYPE_SDI  FrameType = 133 // 0x85 - 站场完整数据(全量)
	FrameType_FRAME_TYPE_SDIQ FrameType = 106 // 0x6A - 站场数据请求
	FrameType_FRAME_TYPE_FIR  FrameType = 101 // 0x65 - 故障信息报告
	FrameType_FRAME_TYPE_RSR  FrameType = 170 // 0xAA - 系统工作状态报告
	FrameType_FRAME_TYPE_BCC  FrameType = 149 // 0x95 - 按钮控制命令
	FrameType_FRAME_TYPE_ACQ  FrameType = 117 // 0x75 - 自律控制请求
	FrameType_FRAME_TYPE_ACA  FrameType = 122 // 0x7A - 自律控制同意
	FrameType_FRAME_TYPE_TSQ  FrameType = 154 // 0x9A - 时间同步请求
	FrameType_FRAME_TYPE_TSD  FrameType = 165 // 0xA5 - 时间同步数据
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0:   "FRAME_TYPE_UNSPECIFIED",
		18:  "FRAME_TYPE_DC2",
		19:  "FRAME_TYPE_DC3",
		6:   "FRAME_TYPE_ACK",
		21:  "FRAME_TYPE_NACK",
		16:  "FRAME_TYPE_VERROR",
		138: "FRAME_TYPE_SDCI",
		133: "FRAME_TYPE_SDI",
		106: "FRAME_TYPE_SDIQ",
		101: "FRAME_TYPE_FIR",
		170: "FRAME_TYPE_RSR",
		149: "FRAME_TYPE_BCC",
		117: "FRAME_TYPE_ACQ",
		122: "FRAME_TYPE_ACA",
		154: "FRAME_TYPE_TSQ",
		165: "FRAME_TYPE_TSD",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_UNSPECIFIED": 0,
		"FRAME_TYPE_DC2":         18,
		"FRAME_TYPE_DC3":         19,
		"FRAME_TYPE_ACK":         6,
		"FRAME_TYPE_NACK":        21,
		"FRAME_TYPE_VERROR":      16,
		"FRAME_TYPE_SDCI":        138,
		"FRAME_TYPE_SDI":         133,
		"FRAME_TYPE_SDIQ":        106,
		"FRAME_TYPE_FIR":         101,
		"FRAME_TYPE_RSR":         170,
		"FRAME_TYPE_BCC":         149,
		"FRAME_TYPE_ACQ":         117,
		"FRAME_TYPE_ACA":         122,
		"FRAME_TYPE_TSQ":         154,
		"FRAME_TYPE_TSD":         165,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cbi_v1_cbi_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_api_proto_cbi_v1_cbi_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{0}
}

// 设备类型
type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	DeviceType_DEVICE_TYPE_TURNOUT     DeviceType = 1
	DeviceType_DEVICE_TYPE_SIGNAL      DeviceType = 2
	DeviceType_DEVICE_TYPE_SECTION     DeviceType = 3
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_TURNOUT",
		2: "DEVICE_TYPE_SIGNAL",
		3: "DEVICE_TYPE_SECTION",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_TURNOUT":     1,
		"DEVICE_TYPE_SIGNAL":      2,
		"DEVICE_TYPE_SECTION":     3,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cbi_v1_cbi_proto_enumTypes[1].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_api_proto_cbi_v1_cbi_proto_enumTypes[1]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{1}
}

// 角色类型
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_MASTER      Role = 1
	Role_ROLE_BACKUP      Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_MASTER",
		2: "ROLE_BACKUP",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_MASTER":      1,
		"ROLE_BACKUP":      2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cbi_v1_cbi_proto_enumTypes[2].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_api_proto_cbi_v1_cbi_proto_enumTypes[2]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{2}
}

// 空消息
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{0}
}

// 帧消息
type Frame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Header    []byte                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                         // 帧头 0x7D
	HeaderLen uint32                 `protobuf:"varint,2,opt,name=header_len,json=headerLen,proto3" json:"header_len,omitempty"` // 首部长度
	Version   uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`                      // 协议版本
	SendSeq   uint32                 `protobuf:"varint,4,opt,name=send_seq,json=sendSeq,proto3" json:"send_seq,omitempty"`       // 发送序号
	AckSeq    uint32                 `protobuf:"varint,5,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`          // 确认序号
	Type      FrameType              `protobuf:"varint,6,opt,name=type,proto3,enum=cbi.v1.FrameType" json:"type,omitempty"`      // 帧类型
	// 以下字段仅对数据帧有效（控制帧无此字段）
	DataLength    *uint32 `protobuf:"varint,7,opt,name=data_length,json=dataLength,proto3,oneof" json:"data_length,omitempty"`
	Data          []byte  `protobuf:"bytes,8,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Crc           uint32  `protobuf:"varint,9,opt,name=crc,proto3" json:"crc,omitempty"` // CRC校验
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{1}
}

func (x *Frame) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Frame) GetHeaderLen() uint32 {
	if x != nil {
		return x.HeaderLen
	}
	return 0
}

func (x *Frame) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Frame) GetSendSeq() uint32 {
	if x != nil {
		return x.SendSeq
	}
	return 0
}

func (x *Frame) GetAckSeq() uint32 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

func (x *Frame) GetType() FrameType {
	if x != nil {
		return x.Type
	}
	return FrameType_FRAME_TYPE_UNSPECIFIED
}

func (x *Frame) GetDataLength() uint32 {
	if x != nil && x.DataLength != nil {
		return *x.DataLength
	}
	return 0
}

func (x *Frame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Frame) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

// 帧请求
type FrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         *Frame                 `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRequest) Reset() {
	*x = FrameRequest{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRequest) ProtoMessage() {}

func (x *FrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRequest.ProtoReflect.Descriptor instead.
func (*FrameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{2}
}

func (x *FrameRequest) GetFrame() *Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

// 帧响应
type FrameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         *Frame                 `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameResponse) Reset() {
	*x = FrameResponse{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameResponse) ProtoMessage() {}

func (x *FrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameResponse.ProtoReflect.Descriptor instead.
func (*FrameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{3}
}

func (x *FrameResponse) GetFrame() *Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *FrameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 设备请求
type DeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRequest) Reset() {
	*x = DeviceRequest{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequest) ProtoMessage() {}

func (x *DeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRequest.ProtoReflect.Descriptor instead.
func (*DeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 设备状态
type DeviceState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          DeviceType             `protobuf:"varint,3,opt,name=type,proto3,enum=cbi.v1.DeviceType" json:"type,omitempty"`
	State         []byte                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceState) Reset() {
	*x = DeviceState{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceState) ProtoMessage() {}

func (x *DeviceState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceState.ProtoReflect.Descriptor instead.
func (*DeviceState) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceState) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DeviceState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceState) GetType() DeviceType {
	if x != nil {
		return x.Type
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *DeviceState) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *DeviceState) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 设置设备状态请求
type SetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	State         []byte                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceRequest) Reset() {
	*x = SetDeviceRequest{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceRequest) ProtoMessage() {}

func (x *SetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceRequest.ProtoReflect.Descriptor instead.
func (*SetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{6}
}

func (x *SetDeviceRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SetDeviceRequest) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

// 设置设备状态响应
type SetDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	NewState      *DeviceState           `protobuf:"bytes,3,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceResponse) Reset() {
	*x = SetDeviceResponse{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceResponse) ProtoMessage() {}

func (x *SetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceResponse.ProtoReflect.Descriptor instead.
func (*SetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{7}
}

func (x *SetDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDeviceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SetDeviceResponse) GetNewState() *DeviceState {
	if x != nil {
		return x.NewState
	}
	return nil
}

// 所有设备状态
type AllDeviceStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceState         `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllDeviceStates) Reset() {
	*x = AllDeviceStates{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllDeviceStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllDeviceStates) ProtoMessage() {}

func (x *AllDeviceStates) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllDeviceStates.ProtoReflect.Descriptor instead.
func (*AllDeviceStates) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{8}
}

func (x *AllDeviceStates) GetDevices() []*DeviceState {
	if x != nil {
		return x.Devices
	}
	return nil
}

// 设置角色请求
type SetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=cbi.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoleRequest) Reset() {
	*x = SetRoleRequest{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleRequest) ProtoMessage() {}

func (x *SetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleRequest.ProtoReflect.Descriptor instead.
func (*SetRoleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{9}
}

func (x *SetRoleRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

// 角色响应
type RoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=cbi.v1.Role" json:"role,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponse) Reset() {
	*x = RoleResponse{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponse) ProtoMessage() {}

func (x *RoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponse.ProtoReflect.Descriptor instead.
func (*RoleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{10}
}

func (x *RoleResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *RoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 场景
type Scenario struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InitialStates []*DeviceState         `protobuf:"bytes,3,rep,name=initial_states,json=initialStates,proto3" json:"initial_states,omitempty"`
	Actions       []*FrameAction         `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{11}
}

func (x *Scenario) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scenario) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Scenario) GetInitialStates() []*DeviceState {
	if x != nil {
		return x.InitialStates
	}
	return nil
}

func (x *Scenario) GetActions() []*FrameAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

// 帧动作
type FrameAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelayMs       int64                  `protobuf:"varint,1,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	SendFrame     *Frame                 `protobuf:"bytes,2,opt,name=send_frame,json=sendFrame,proto3" json:"send_frame,omitempty"`
	ExpectFrame   *Frame                 `protobuf:"bytes,3,opt,name=expect_frame,json=expectFrame,proto3" json:"expect_frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameAction) Reset() {
	*x = FrameAction{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameAction) ProtoMessage() {}

func (x *FrameAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameAction.ProtoReflect.Descriptor instead.
func (*FrameAction) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{12}
}

func (x *FrameAction) GetDelayMs() int64 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *FrameAction) GetSendFrame() *Frame {
	if x != nil {
		return x.SendFrame
	}
	return nil
}

func (x *FrameAction) GetExpectFrame() *Frame {
	if x != nil {
		return x.ExpectFrame
	}
	return nil
}

// 场景请求
type ScenarioRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ScenarioRequest_LoadName
	//	*ScenarioRequest_SaveScenario
	//	*ScenarioRequest_DeleteName
	Request       isScenarioRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioRequest) Reset() {
	*x = ScenarioRequest{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioRequest) ProtoMessage() {}

func (x *ScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioRequest.ProtoReflect.Descriptor instead.
func (*ScenarioRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{13}
}

func (x *ScenarioRequest) GetRequest() isScenarioRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ScenarioRequest) GetLoadName() string {
	if x != nil {
		if x, ok := x.Request.(*ScenarioRequest_LoadName); ok {
			return x.LoadName
		}
	}
	return ""
}

func (x *ScenarioRequest) GetSaveScenario() *Scenario {
	if x != nil {
		if x, ok := x.Request.(*ScenarioRequest_SaveScenario); ok {
			return x.SaveScenario
		}
	}
	return nil
}

func (x *ScenarioRequest) GetDeleteName() string {
	if x != nil {
		if x, ok := x.Request.(*ScenarioRequest_DeleteName); ok {
			return x.DeleteName
		}
	}
	return ""
}

type isScenarioRequest_Request interface {
	isScenarioRequest_Request()
}

type ScenarioRequest_LoadName struct {
	LoadName string `protobuf:"bytes,1,opt,name=load_name,json=loadName,proto3,oneof"`
}

type ScenarioRequest_SaveScenario struct {
	SaveScenario *Scenario `protobuf:"bytes,2,opt,name=save_scenario,json=saveScenario,proto3,oneof"`
}

type ScenarioRequest_DeleteName struct {
	DeleteName string `protobuf:"bytes,3,opt,name=delete_name,json=deleteName,proto3,oneof"`
}

func (*ScenarioRequest_LoadName) isScenarioRequest_Request() {}

func (*ScenarioRequest_SaveScenario) isScenarioRequest_Request() {}

func (*ScenarioRequest_DeleteName) isScenarioRequest_Request() {}

// 场景响应
type ScenarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Scenario      *Scenario              `protobuf:"bytes,3,opt,name=scenario,proto3" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioResponse) Reset() {
	*x = ScenarioResponse{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioResponse) ProtoMessage() {}

func (x *ScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioResponse.ProtoReflect.Descriptor instead.
func (*ScenarioResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{14}
}

func (x *ScenarioResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScenarioResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScenarioResponse) GetScenario() *Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

// 场景列表响应
type ScenarioListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioListResponse) Reset() {
	*x = ScenarioListResponse{}
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioListResponse) ProtoMessage() {}

func (x *ScenarioListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cbi_v1_cbi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioListResponse.ProtoReflect.Descriptor instead.
func (*ScenarioListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cbi_v1_cbi_proto_rawDescGZIP(), []int{15}
}

func (x *ScenarioListResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_api_proto_cbi_v1_cbi_proto protoreflect.FileDescriptor

const file_api_proto_cbi_v1_cbi_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/cbi/v1/cbi.proto\x12\x06cbi.v1\"\a\n" +
	"\x05Empty\"\x9d\x02\n" +
	"\x05Frame\x12\x16\n" +
	"\x06header\x18\x01 \x01(\fR\x06header\x12\x1d\n" +
	"\n" +
	"header_len\x18\x02 \x01(\rR\theaderLen\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12\x19\n" +
	"\bsend_seq\x18\x04 \x01(\rR\asendSeq\x12\x17\n" +
	"\aack_seq\x18\x05 \x01(\rR\x06ackSeq\x12%\n" +
	"\x04type\x18\x06 \x01(\x0e2\x11.cbi.v1.FrameTypeR\x04type\x12$\n" +
	"\vdata_length\x18\a \x01(\rH\x00R\n" +
	"dataLength\x88\x01\x01\x12\x17\n" +
	"\x04data\x18\b \x01(\fH\x01R\x04data\x88\x01\x01\x12\x10\n" +
	"\x03crc\x18\t \x01(\rR\x03crcB\x0e\n" +
	"\f_data_lengthB\a\n" +
	"\x05_data\"3\n" +
	"\fFrameRequest\x12#\n" +
	"\x05frame\x18\x01 \x01(\v2\r.cbi.v1.FrameR\x05frame\"J\n" +
	"\rFrameResponse\x12#\n" +
	"\x05frame\x18\x01 \x01(\v2\r.cbi.v1.FrameR\x05frame\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"9\n" +
	"\rDeviceRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x97\x01\n" +
	"\vDeviceState\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.cbi.v1.DeviceTypeR\x04type\x12\x14\n" +
	"\x05state\x18\x04 \x01(\fR\x05state\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\">\n" +
	"\x10SetDeviceRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x14\n" +
	"\x05state\x18\x02 \x01(\fR\x05state\"u\n" +
	"\x11SetDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x120\n" +
	"\tnew_state\x18\x03 \x01(\v2\x13.cbi.v1.DeviceStateR\bnewState\"@\n" +
	"\x0fAllDeviceStates\x12-\n" +
	"\adevices\x18\x01 \x03(\v2\x13.cbi.v1.DeviceStateR\adevices\"2\n" +
	"\x0eSetRoleRequest\x12 \n" +
	"\x04role\x18\x01 \x01(\x0e2\f.cbi.v1.RoleR\x04role\"J\n" +
	"\fRoleResponse\x12 \n" +
	"\x04role\x18\x01 \x01(\x0e2\f.cbi.v1.RoleR\x04role\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xab\x01\n" +
	"\bScenario\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\x0einitial_states\x18\x03 \x03(\v2\x13.cbi.v1.DeviceStateR\rinitialStates\x12-\n" +
	"\aactions\x18\x04 \x03(\v2\x13.cbi.v1.FrameActionR\aactions\"\x88\x01\n" +
	"\vFrameAction\x12\x19\n" +
	"\bdelay_ms\x18\x01 \x01(\x03R\adelayMs\x12,\n" +
	"\n" +
	"send_frame\x18\x02 \x01(\v2\r.cbi.v1.FrameR\tsendFrame\x120\n" +
	"\fexpect_frame\x18\x03 \x01(\v2\r.cbi.v1.FrameR\vexpectFrame\"\x97\x01\n" +
	"\x0fScenarioRequest\x12\x1d\n" +
	"\tload_name\x18\x01 \x01(\tH\x00R\bloadName\x127\n" +
	"\rsave_scenario\x18\x02 \x01(\v2\x10.cbi.v1.ScenarioH\x00R\fsaveScenario\x12!\n" +
	"\vdelete_name\x18\x03 \x01(\tH\x00R\n" +
	"deleteNameB\t\n" +
	"\arequest\"p\n" +
	"\x10ScenarioResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12,\n" +
	"\bscenario\x18\x03 \x01(\v2\x10.cbi.v1.ScenarioR\bscenario\",\n" +
	"\x14ScenarioListResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names*\xdf\x02\n" +
	"\tFrameType\x12\x1a\n" +
	"\x16FRAME_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eFRAME_TYPE_DC2\x10\x12\x12\x12\n" +
	"\x0eFRAME_TYPE_DC3\x10\x13\x12\x12\n" +
	"\x0eFRAME_TYPE_ACK\x10\x06\x12\x13\n" +
	"\x0fFRAME_TYPE_NACK\x10\x15\x12\x15\n" +
	"\x11FRAME_TYPE_VERROR\x10\x10\x12\x14\n" +
	"\x0fFRAME_TYPE_SDCI\x10\x8a\x01\x12\x13\n" +
	"\x0eFRAME_TYPE_SDI\x10\x85\x01\x12\x13\n" +
	"\x0fFRAME_TYPE_SDIQ\x10j\x12\x12\n" +
	"\x0eFRAME_TYPE_FIR\x10e\x12\x13\n" +
	"\x0eFRAME_TYPE_RSR\x10\xaa\x01\x12\x13\n" +
	"\x0eFRAME_TYPE_BCC\x10\x95\x01\x12\x12\n" +
	"\x0eFRAME_TYPE_ACQ\x10u\x12\x12\n" +
	"\x0eFRAME_TYPE_ACA\x10z\x12\x13\n" +
	"\x0eFRAME_TYPE_TSQ\x10\x9a\x01\x12\x13\n" +
	"\x0eFRAME_TYPE_TSD\x10\xa5\x01*s\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DEVICE_TYPE_TURNOUT\x10\x01\x12\x16\n" +
	"\x12DEVICE_TYPE_SIGNAL\x10\x02\x12\x17\n" +
	"\x13DEVICE_TYPE_SECTION\x10\x03*>\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROLE_MASTER\x10\x01\x12\x0f\n" +
	"\vROLE_BACKUP\x10\x022\x83\x05\n" +
	"\fCBISimulator\x12>\n" +
	"\vFrameStream\x12\x14.cbi.v1.FrameRequest\x1a\x15.cbi.v1.FrameResponse(\x010\x01\x12<\n" +
	"\x0eGetDeviceState\x12\x15.cbi.v1.DeviceRequest\x1a\x13.cbi.v1.DeviceState\x12E\n" +
	"\x0eSetDeviceState\x12\x18.cbi.v1.SetDeviceRequest\x1a\x19.cbi.v1.SetDeviceResponse\x12<\n" +
	"\x12GetAllDeviceStates\x12\r.cbi.v1.Empty\x1a\x17.cbi.v1.AllDeviceStates\x127\n" +
	"\aSetRole\x12\x16.cbi.v1.SetRoleRequest\x1a\x14.cbi.v1.RoleResponse\x12.\n" +
	"\aGetRole\x12\r.cbi.v1.Empty\x1a\x14.cbi.v1.RoleResponse\x12A\n" +
	"\fLoadScenario\x12\x17.cbi.v1.ScenarioRequest\x1a\x18.cbi.v1.ScenarioResponse\x12A\n" +
	"\fSaveScenario\x12\x17.cbi.v1.ScenarioRequest\x1a\x18.cbi.v1.ScenarioResponse\x12C\n" +
	"\x0eDeleteScenario\x12\x17.cbi.v1.ScenarioRequest\x1a\x18.cbi.v1.ScenarioResponse\x12<\n" +
	"\rListScenarios\x12\r.cbi.v1.Empty\x1a\x1c.cbi.v1.ScenarioListResponseB(Z&cbi-simulator/internal/pb/cbi/v1;cbiv1b\x06proto3"

var (
	file_api_proto_cbi_v1_cbi_proto_rawDescOnce sync.Once
	file_api_proto_cbi_v1_cbi_proto_rawDescData []byte
)

func file_api_proto_cbi_v1_cbi_proto_rawDescGZIP() []byte {
	file_api_proto_cbi_v1_cbi_proto_rawDescOnce.Do(func() {
		file_api_proto_cbi_v1_cbi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cbi_v1_cbi_proto_rawDesc), len(file_api_proto_cbi_v1_cbi_proto_rawDesc)))
	})
	return file_api_proto_cbi_v1_cbi_proto_rawDescData
}

var file_api_proto_cbi_v1_cbi_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_cbi_v1_cbi_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_cbi_v1_cbi_proto_goTypes = []any{
	(FrameType)(0),               // 0: cbi.v1.FrameType
	(DeviceType)(0),              // 1: cbi.v1.DeviceType
	(Role)(0),                    // 2: cbi.v1.Role
	(*Empty)(nil),                // 3: cbi.v1.Empty
	(*Frame)(nil),                // 4: cbi.v1.Frame
	(*FrameRequest)(nil),         // 5: cbi.v1.FrameRequest
	(*FrameResponse)(nil),        // 6: cbi.v1.FrameResponse
	(*DeviceRequest)(nil),        // 7: cbi.v1.DeviceRequest
	(*DeviceState)(nil),          // 8: cbi.v1.DeviceState
	(*SetDeviceRequest)(nil),     // 9: cbi.v1.SetDeviceRequest
	(*SetDeviceResponse)(nil),    // 10: cbi.v1.SetDeviceResponse
	(*AllDeviceStates)(nil),      // 11: cbi.v1.AllDeviceStates
	(*SetRoleRequest)(nil),       // 12: cbi.v1.SetRoleRequest
	(*RoleResponse)(nil),         // 13: cbi.v1.RoleResponse
	(*Scenario)(nil),             // 14: cbi.v1.Scenario
	(*FrameAction)(nil),          // 15: cbi.v1.FrameAction
	(*ScenarioRequest)(nil),      // 16: cbi.v1.ScenarioRequest
	(*ScenarioResponse)(nil),     // 17: cbi.v1.ScenarioResponse
	(*ScenarioListResponse)(nil), // 18: cbi.v1.ScenarioListResponse
}
var file_api_proto_cbi_v1_cbi_proto_depIdxs = []int32{
	0,  // 0: cbi.v1.Frame.type:type_name -> cbi.v1.FrameType
	4,  // 1: cbi.v1.FrameRequest.frame:type_name -> cbi.v1.Frame
	4,  // 2: cbi.v1.FrameResponse.frame:type_name -> cbi.v1.Frame
	1,  // 3: cbi.v1.DeviceState.type:type_name -> cbi.v1.DeviceType
	8,  // 4: cbi.v1.SetDeviceResponse.new_state:type_name -> cbi.v1.DeviceState
	8,  // 5: cbi.v1.AllDeviceStates.devices:type_name -> cbi.v1.DeviceState
	2,  // 6: cbi.v1.SetRoleRequest.role:type_name -> cbi.v1.Role
	2,  // 7: cbi.v1.RoleResponse.role:type_name -> cbi.v1.Role
	8,  // 8: cbi.v1.Scenario.initial_states:type_name -> cbi.v1.DeviceState
	15, // 9: cbi.v1.Scenario.actions:type_name -> cbi.v1.FrameAction
	4,  // 10: cbi.v1.FrameAction.send_frame:type_name -> cbi.v1.Frame
	4,  // 11: cbi.v1.FrameAction.expect_frame:type_name -> cbi.v1.Frame
	14, // 12: cbi.v1.ScenarioRequest.save_scenario:type_name -> cbi.v1.Scenario
	14, // 13: cbi.v1.ScenarioResponse.scenario:type_name -> cbi.v1.Scenario
	5,  // 14: cbi.v1.CBISimulator.FrameStream:input_type -> cbi.v1.FrameRequest
	7,  // 15: cbi.v1.CBISimulator.GetDeviceState:input_type -> cbi.v1.DeviceRequest
	9,  // 16: cbi.v1.CBISimulator.SetDeviceState:input_type -> cbi.v1.SetDeviceRequest
	3,  // 17: cbi.v1.CBISimulator.GetAllDeviceStates:input_type -> cbi.v1.Empty
	12, // 18: cbi.v1.CBISimulator.SetRole:input_type -> cbi.v1.SetRoleRequest
	3,  // 19: cbi.v1.CBISimulator.GetRole:input_type -> cbi.v1.Empty
	16, // 20: cbi.v1.CBISimulator.LoadScenario:input_type -> cbi.v1.ScenarioRequest
	16, // 21: cbi.v1.CBISimulator.SaveScenario:input_type -> cbi.v1.ScenarioRequest
	16, // 22: cbi.v1.CBISimulator.DeleteScenario:input_type -> cbi.v1.ScenarioRequest
	3,  // 23: cbi.v1.CBISimulator.ListScenarios:input_type -> cbi.v1.Empty
	6,  // 24: cbi.v1.CBISimulator.FrameStream:output_type -> cbi.v1.FrameResponse
	8,  // 25: cbi.v1.CBISimulator.GetDeviceState:output_type -> cbi.v1.DeviceState
	10, // 26: cbi.v1.CBISimulator.SetDeviceState:output_type -> cbi.v1.SetDeviceResponse
	11, // 27: cbi.v1.CBISimulator.GetAllDeviceStates:output_type -> cbi.v1.AllDeviceStates
	13, // 28: cbi.v1.CBISimulator.SetRole:output_type -> cbi.v1.RoleResponse
	13, // 29: cbi.v1.CBISimulator.GetRole:output_type -> cbi.v1.RoleResponse
	17, // 30: cbi.v1.CBISimulator.LoadScenario:output_type -> cbi.v1.ScenarioResponse
	17, // 31: cbi.v1.CBISimulator.SaveScenario:output_type -> cbi.v1.ScenarioResponse
	17, // 32: cbi.v1.CBISimulator.DeleteScenario:output_type -> cbi.v1.ScenarioResponse
	18, // 33: cbi.v1.CBISimulator.ListScenarios:output_type -> cbi.v1.ScenarioListResponse
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_cbi_v1_cbi_proto_init() }
func file_api_proto_cbi_v1_cbi_proto_init() {
	if File_api_proto_cbi_v1_cbi_proto != nil {
		return
	}
	file_api_proto_cbi_v1_cbi_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_proto_cbi_v1_cbi_proto_msgTypes[13].OneofWrappers = []any{
		(*ScenarioRequest_LoadName)(nil),
		(*ScenarioRequest_SaveScenario)(nil),
		(*ScenarioRequest_DeleteName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cbi_v1_cbi_proto_rawDesc), len(file_api_proto_cbi_v1_cbi_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cbi_v1_cbi_proto_goTypes,
		DependencyIndexes: file_api_proto_cbi_v1_cbi_proto_depIdxs,
		EnumInfos:         file_api_proto_cbi_v1_cbi_proto_enumTypes,
		MessageInfos:      file_api_proto_cbi_v1_cbi_proto_msgTypes,
	}.Build()
	File_api_proto_cbi_v1_cbi_proto = out.File
	file_api_proto_cbi_v1_cbi_proto_goTypes = nil
	file_api_proto_cbi_v1_cbi_proto_depIdxs = nil
}
